# Array - https://goo.gl/njVmPU

In [1]:
import numpy as np


In [95]:
lst=[[1,2,3],
    [4,5,6]]
    
arr2d = np.array(lst)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2d.size

6

In [8]:
arr2d.shape

(2, 3)

In [9]:
arr2d.itemsize

8

In [12]:
arr2d.dtype

dtype('int64')

In [13]:
arr_float = arr2d.astype(np.float32)
arr_float

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [14]:
arr4x5 = [[1,2,3,4,5],
         [6,7,8,9,10],
         [11,12,13,14,15],
         [16,17,18,19,20]]
arr4x5=np.array(arr4x5,dtype='float32')

In [15]:
arr4x5

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.diag((8,8))

array([[8, 0],
       [0, 8]])

In [30]:
np.random.rand(3,4)   #is used to generate a random matrix of specified dimensions

array([[0.29853149, 0.25601727, 0.44053032, 0.63594143],
       [0.29809302, 0.23433453, 0.32370187, 0.39300414],
       [0.67659357, 0.91571545, 0.37920226, 0.49478695]])

In [31]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [32]:
np.arange(45)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [33]:
np.arange(5,78)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77])

In [34]:
np.arange(-15,7)

array([-15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,
        -2,  -1,   0,   1,   2,   3,   4,   5,   6])

In [35]:
np.arange(4,15,2)   # (start,stop,step)

array([ 4,  6,  8, 10, 12, 14])

In [36]:
np.arange(0,15,5)

array([ 0,  5, 10])

In [38]:
np.linspace(0.,1.,num=5)     #to divide the start and end values in equal no. of steps as mentioned in the 'num' variable

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.arange(1,40,2)    # odd no. in array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [40]:
arr_ind = np.array([1,2,3])
arr_ind[0]

1

In [41]:
arr_ind[2]

3

In [42]:
arr_ind[:3]

array([1, 2, 3])

In [45]:
arr_ind[:2]       

array([1, 2])

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2d[0,:]

array([1, 2, 3])

In [49]:
arr2d[0,:1]

array([1])

In [50]:
arr2d[0,:2]

array([1, 2])

In [51]:
arr2d[1,:2]

array([4, 5])

In [52]:
arr4x5

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [53]:
arr4x5[2,:]   # it means iy access all the columns

array([11., 12., 13., 14., 15.], dtype=float32)

In [54]:
arr4x5[:,2]   #in means it access all the rows

array([ 3.,  8., 13., 18.], dtype=float32)

In [55]:
arr4x5[:,:3]     #to access first three columns

array([[ 1.,  2.,  3.],
       [ 6.,  7.,  8.],
       [11., 12., 13.],
       [16., 17., 18.]], dtype=float32)

In [57]:
arr4x5[:2,:]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)

In [58]:
arr4x5[:4,:4]  # here it will take 4 rows and 4 columns

array([[ 1.,  2.,  3.,  4.],
       [ 6.,  7.,  8.,  9.],
       [11., 12., 13., 14.],
       [16., 17., 18., 19.]], dtype=float32)

In [60]:
arr4x5[-2,:]   # using negative indexing

array([11., 12., 13., 14., 15.], dtype=float32)

In [61]:
arr4x5[-1,-1]

20.0

In [63]:
arr4x5[:-2,:]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]], dtype=float32)

In [64]:
arr4x5[:,-1]

array([ 5., 10., 15., 20.], dtype=float32)

In [65]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(np.add(arr2d,4))    # the original add is added with 4
arr2d   # the original array doesn't change

[[ 5  6  7]
 [ 8  9 10]]


array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
print(np.subtract(arr2d,2))     # subtracts 2 from the original array

[[-1  0  1]
 [ 2  3  4]]


In [68]:
arr2d*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [69]:
arr4x5

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [70]:
arr4x5*2

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.]], dtype=float32)

In [71]:
arr4x5    # original doesn't change

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [72]:
arr4x5**2

array([[  1.,   4.,   9.,  16.,  25.],
       [ 36.,  49.,  64.,  81., 100.],
       [121., 144., 169., 196., 225.],
       [256., 289., 324., 361., 400.]], dtype=float32)

In [74]:
arr4x5*.2

array([[0.2      , 0.4      , 0.6      , 0.8      , 1.       ],
       [1.2      , 1.4      , 1.6      , 1.8000001, 2.       ],
       [2.2      , 2.4      , 2.6000001, 2.8      , 3.       ],
       [3.2      , 3.4      , 3.6000001, 3.8      , 4.       ]],
      dtype=float32)

In [75]:
arr4x5     # after all these operation the original array still remains the same

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)

In [79]:
newarr=np.array([[1,2,3],[4,5,6]])
newarr


array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.add.reduce(newarr)     # column wise addition

array([5, 7, 9])

In [81]:
np.add.reduce(newarr, axis=1)

array([ 6, 15])

In [84]:
np.max(newarr)

6

In [85]:
np.min(newarr)

1

In [89]:
np.array([1,2,3]) + 1    # add every element by 1

array([2, 3, 4])

In [90]:
np.array([1,2,3]) - 1    # subtracts every element by 1

array([0, 1, 2])

In [101]:
arr1d = np.array([1,2,3,4,5,6])
arr1d

array([1, 2, 3, 4, 5, 6])

In [102]:
arr2d_view = arr1d.reshape(2,3)
arr2d_view

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
arr2d = np.array([[100,101,102],[103,104,105]])
arr2d

array([[100, 101, 102],
       [103, 104, 105]])

In [111]:
arr2d.reshape(-1)

array([100, 101, 102, 103, 104, 105])

In [112]:
arr2d

array([[100, 101, 102],
       [103, 104, 105]])

In [113]:
arr2d.ravel()

array([100, 101, 102, 103, 104, 105])